foreground   #ebe1ce
background   #090b0f
cursor       #ebe1ce

color0       #090b0f
color8       #a49d90
color1       #916D58
color9       #916D58
color2       #C97B55
color10      #C97B55
color3       #D1A06A
color11      #D1A06A
color4       #7E7B83
color12      #7E7B83
color5       #A69891
color13      #A69891
color6       #CBB6A3
color14      #CBB6A3
color7       #ebe1ce
color15      #ebe1ce
