# Shell variables
# Generated by 'wal'
wallpaper='/home/nyxarch/Pictures/Wallpapers/wallhaven-4vdlpl.jpg'

# Special
background='#090b0f'
foreground='#ebe1ce'
cursor='#ebe1ce'

# Colors
color0='#090b0f'
color1='#916D58'
color2='#C97B55'
color3='#D1A06A'
color4='#7E7B83'
color5='#A69891'
color6='#CBB6A3'
color7='#ebe1ce'
color8='#a49d90'
color9='#916D58'
color10='#C97B55'
color11='#D1A06A'
color12='#7E7B83'
color13='#A69891'
color14='#CBB6A3'
color15='#ebe1ce'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
